#!/bin/bash

DATADIR="`pwd`/data" # This is where fastq/bam and reference files should be located.

EAGER_IMG="./dependencies/EAGER-GUI_latest.sif" # This is the pulled singularity image

XMLDIR=$1

singularity exec -B "${DATADIR}:/data"  ${EAGER_IMG} eagercli ${XMLDIR}
